### ISSUE TITLE
rc4 tip does not compile aether/node tests: #832 added abstract ManageableNode.schemaOrchestrator(), three #826 test doubles never implemented it; #832 was merged over COMPILATION ERROR

### ISSUE THREAD

**Issue by siy** [pragmaticalabs/pragmatica#855]
**Symptom.** On the `release-1.0.0-rc4` tip (`180e66b20`) `aether/node` test sources do not compile:

```
BlueprintDeployStatusTest.java:[317,13] DeployManageableNode is not abstract and does not override abstract method schemaOrchestrator() in ManageableNode
BlueprintStatusAggregationTest.java:[458,13] StatusManageableNode ...
BlueprintServiceTest.java:[457,17] LiveManageableNode ...
```

CI (`mvn install -B -pl '!examples'`, fail-fast) stops at `aether/node` — so the second base red, #854 (dead-surface gate), is only reachable once this is fixed, and nothing after `aether/node` in the reactor has been exercised by CI on the tip.

**Mechanism.** #832 (`a44d02655`, #543) added the abstract `SchemaOrchestratorService schemaOrchestrator()` to `ManageableNode` (:213) and updated the test doubles its branch knew about. #826 (#759, merged 06:13 UTC) had added three anonymous `ManageableNode` doubles the #832 branch never contained. GitHub's merge ref for #832 combined both, and #832's own `build-and-test` reported `COMPILATION ERROR` on exactly these three files (11:10 UTC); the PR was recorded READY/MERGEABLE and merged with `--admin` at 17:00 UTC. `mergeable` does not mean checks-green.

**Fix.** Implement `schemaOrchestrator()` in the three doubles the way the #832-era doubles do (`SchemaRouteStatusTest`, `SchemaRoutesBaselineTest`); test-only change. Landing in the same PR as #854 so that ONE PR can show a green `build-and-test` on rc4 — two separate PRs could each only be merged over the other's red.

**Process.** Every PR state line must carry the CI conclusion per job before "READY" is used; a merge line is issued only for PRs whose `build-and-test` is green or whose failure is proven to be the base's.

**Comment by siy** [comment]
Closing on evidence from PR #857 (rc4).

The defect: `aether/node`'s test sources did not compile on the release branch. #832 (#543) made `schemaOrchestrator()` abstract on `ManageableNode`; three anonymous test doubles added earlier by #826 (#759) never got the override, and the two PRs' branches each compiled in isolation. GitHub's merge combined them, #832's own `build-and-test` reported `COMPILATION ERROR` on exactly those three files, and it was merged anyway — so from that merge until this fix, CI stopped at `aether/node` and nothing after it in the reactor was exercised, including the dead-surface gate that was also red underneath (#854).

What changed: the three doubles (`BlueprintDeployStatusTest`, `BlueprintStatusAggregationTest`, `BlueprintServiceTest`) implement `schemaOrchestrator()` through each file's existing `unsupported(...)` convention — none of those routes calls it, unlike the #832-era doubles which return a real orchestrator because their routes do [verified: `aether/node` full suite, 1132 tests, 0 failures — the first green run of that module since the #832 merge, and no other breakage was hiding behind the compile error].

Process consequence, recorded as a rule: a PR's state line carries the CI conclusion per job before the word READY is used, and a merge line names only PRs whose `build-and-test` is green or whose failure is proven to belong to the base. "Mergeable" answers whether a branch conflicts, not whether it builds.
